"""Emit the main-text table of peak estimate and scan-corrected verdict by index construction.

Writes manuscript/src/generated/index_verdict_table.tex from index_verdict_table.json.
"""

from __future__ import annotations
# --- replication-package prelude (added by build_package.py) ------------------
# The original research scripts pointed at an absolute project root. In this
# package the repository locates itself, so it runs from any checkout location.
from pathlib import Path as _RepoPath
_REPO = str(_RepoPath(__file__).resolve().parents[2])
# ------------------------------------------------------------------------------

import hashlib
import json
from pathlib import Path

ROOT = _RepoPath(_REPO)
SRC = ROOT / "analysis/15_unambiguous_index/index_verdict_table.json"
OUT = ROOT / "manuscript/src/generated/index_verdict_table.tex"

CAPTION = (
    "\\textbf{The scan-corrected verdict is a joint property of the estimate and the "
    "series' persistence.} Each construction of the search index is correlated with the same "
    "climate-coverage series and judged against its own two-sided 95\\% max-statistic band, "
    "computed over all 79 scanned leads by circular shifts of that index. Bands are recomputed "
    "here under one common procedure (2{,}000 shifts, common seed) so they are comparable across "
    "rows; the primary row's band agrees with the archived value ($0.346$) to within Monte-Carlo "
    "error. Excluding the single-term index, the peak estimates span $0.375$--$0.439$ while the "
    "bands span $0.345$--$0.437$, and the verdicts split."
)


def main() -> None:
    data = json.loads(SRC.read_text())
    lines = [
        f"% Generated by analysis/15_unambiguous_index/{Path(__file__).name}.",
        f"% Source SHA-256: {hashlib.sha256(SRC.read_bytes()).hexdigest()}",
        "\\begin{table}[H]",
        "\\centering",
        "\\footnotesize",
        f"\\caption{{{CAPTION}}}",
        "\\label{tab:index_verdicts}",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "\\textbf{Index construction} & Peak $L$ & Peak $r$ & Null band & Lag-1 & Verdict \\\\",
        "\\midrule",
    ]
    for row in data["rows"]:
        verdict = "clears" if row["clears_band"] else "does not clear"
        name = row["construction"].replace("&", "\\&")
        lines.append(
            f"{name} & {row['peak_lead_weeks']} & {row['peak_r']:.3f} & "
            f"$\\pm{row['null_band_95']:.3f}$ & {row['lag1_autocorrelation']:.2f} & {verdict} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
