"""Emit the SI table for the primary token relevance audit.

The primary audit (`audit_precision_table.csv`) is the one that defines the
corpus used throughout the paper: 33 tokens, 808 sampled articles, two coding
questions (construct precision and climate relatedness), within-model
inter-prompt agreement. The separate phase-2 embedding re-code is tabulated
elsewhere and is not the operative screen.

Writes manuscript/src/generated/token_audit_primary_table.tex.
"""

from __future__ import annotations
# --- replication-package prelude (added by build_package.py) ------------------
# The original research scripts pointed at an absolute project root. In this
# package the repository locates itself, so it runs from any checkout location.
from pathlib import Path as _RepoPath
_REPO = str(_RepoPath(__file__).resolve().parents[2])
# ------------------------------------------------------------------------------

import hashlib
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "analysis" / "06_token_audit" / "audit_precision_table.csv"
OUT = ROOT / "manuscript" / "src" / "generated" / "token_audit_primary_table.tex"

CAPTION = (
    "Primary news-token relevance audit. Every token with at least one corpus match was "
    "audited on a stratified random sample of matched articles ($n$ per token; 808 articles "
    "in total). $k_{\\text{con}}$ counts articles judged to treat the token's intended "
    "construct substantively and $\\hat p_{\\text{con}}$ is the corresponding precision; "
    "$\\hat p_{\\text{cli}}$ is the share judged to be about climate or environmental issues "
    "at all. Wilson 95\\% intervals in brackets. ``Agree.'' is the raw agreement between the "
    "two instruction lenses before adjudication. All codes are model-generated and await the "
    "blinded human validation described in the main text."
)


def _fmt(value: float) -> str:
    return f"{value:.2f}"


def build() -> str:
    table = pd.read_csv(SRC)
    table = table.sort_values(["family", "prec_named"], ascending=[True, False])

    lines = [
        f"% Generated by analysis/06_token_audit/{Path(__file__).name}.",
        f"% Source SHA-256: {hashlib.sha256(SRC.read_bytes()).hexdigest()}",
        "\\begingroup",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{longtable}{llrrccc}",
        f"\\caption{{{CAPTION}}}\\label{{tab:si_audit_primary}}\\\\",
        "\\toprule",
        "Family & Token & $n$ & $k_{\\text{con}}$ & $\\hat p_{\\text{con}}$ [95\\% CI] "
        "& $\\hat p_{\\text{cli}}$ [95\\% CI] & Agree. \\\\",
        "\\midrule",
        "\\endfirsthead",
        "\\multicolumn{7}{l}{\\textit{Table \\ref{tab:si_audit_primary} continued}}\\\\",
        "\\toprule",
        "Family & Token & $n$ & $k_{\\text{con}}$ & $\\hat p_{\\text{con}}$ [95\\% CI] "
        "& $\\hat p_{\\text{cli}}$ [95\\% CI] & Agree. \\\\",
        "\\midrule",
        "\\endhead",
        "\\midrule",
        "\\multicolumn{7}{r}{\\textit{Continued on next page}}\\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
    ]

    for _, row in table.iterrows():
        family = "climate" if row["family"] == "climate" else "geo"
        token = str(row["token"]).replace("&", "\\&")
        lines.append(
            f"{family} & \\texttt{{{token}}} & {int(row['n'])} & {int(row['k_named'])} & "
            f"{_fmt(row['prec_named'])} {row['ci_named']} & "
            f"{_fmt(row['prec_climate'])} {row['ci_climate']} & "
            f"{_fmt(row['agreement'])} \\\\"
        )

    lines += ["\\end{longtable}", "\\endgroup", ""]
    return "\n".join(lines)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
